### ISSUE TITLE
Save tiles as well as tokens

### ISSUE THREAD

**Issue by kunxin-chor** [spetzel2020/quick-encounters#10]
Is it possible to save tiles as well as tokens? This allows DM to customize tiles on maps as well.

**Comment by opus1217** [comment]
It is not currently possible to do this, but I'm intrigued. Can you describe the workflow for how this would be used?

**Comment by kenpoh01** [comment]
I'd also be interested in this.  I have maps where I have hidden tiles in scenes that are revealed to players, usually with a macro.

**Comment by spetzel2020** [comment]
Am going to look at this next. I don't think it's insurmountable, but is of course different than Actors/Tokens so may take me a bit.

**Comment by thre-z** [comment]
This would be a great feature to have. Tiles (and also drawings?) would be a huge benefit. 

Imagine a caravan of enemies encountered on the road as a part of a random encounter. QE could drop not only the tokens, but also their cart and a drawing with the Vehicles and Mounts details all in one go. 

At least, that's how I imagine it being done.

**Comment by spetzel2020** [comment]
I've started on 0.7 with "adding tiles" as one of the first additions. That should also give me a handle on other assets like drawings. I'm also thinking of queueing up a track to play (certainly I switch to "combat music" when combat starts in my games)

**Comment by kunxin-chor** [comment]
Another use case would be reusing back the same plain battemat, but with tiles as customization. Having music tracks will also be fantastic too.

**Comment by spetzel2020** [comment]
Tiles added in v0.7; playlists/tracks coming soon!
