### ISSUE TITLE
QE not creating map notes Foundry v9 error: Uncaught Reference Error at QuickEncounter.js:541 : JournalEntryPage is not defined

### ISSUE THREAD

**Issue by benik-96** [spetzel2020/quick-encounters#112]
Quick encounters won't produce a map note automatically and can't be dragged onto the scene either.

Video:
https://user-images.githubusercontent.com/115142629/194339055-96337d4a-b4ca-4fa0-a905-764fcfcad19a.mp4

Console Log:
![QE issue](https://user-images.githubusercontent.com/115142629/194340169-49d810dd-f83d-4224-8f3b-6d1df21dccd0.png)

not a terrible issue as encounters can still be ran, more a matter of convenience

**Comment by benik-96** [comment]
Second Video
https://user-images.githubusercontent.com/115142629/194343383-fd81c556-bd1e-4ac9-9cf2-1ca565c7659a.mp4

**Comment by spetzel2020** [comment]
Thanks for creating! This will make it much easier to troubleshoot and fix.

**Comment by spetzel2020** [comment]
Fixed and Released in 1.0.8
