### ISSUE TITLE
Feature Request: (Optionally) Automatically add all player tokens

### ISSUE THREAD

**Issue by DrMcCoy** [spetzel2020/quick-encounters#123]
It would be great if running a QE had an option to automatically add all player characters that have a token in the current scene to the combat.

Right now, I have to trigger the QE, and the manually add the PCs to the combat. Sure, not a huge effort, but it would be nice if I wouldn't have to do that.

It could be done with an extra dialog box when clicking the "Run QE" button (with a config option to disable this dialog box) or some kind of checkbox when creating the QE. Not sure what the best way would be, either sounds fine to me.

**Comment by spetzel2020** [comment]
Very good idea. It's easy to identify Friendly tokens, but I assume for PCs
you want those who are logged in and assigned. What about PCs not logged in
but present in the Scene?

**Comment by DrMcCoy** [comment]
Hmm, yeah, as a DM, if possible, I'd probably want only the PCs that are actually logged in. At least that's what I usually do, when a player can't make it, we're treating the character as being there physically, but not active.

Filtering for PCs should work with `canvas.tokens.placeables.filter(t => t.actor.hasPlayerOwner === true)`, right? No idea how to easily get from there to the owner and logged-in state, though.

However, in one of my groups, the players agreed to have owner on all PCs, so that wouldn't make any different there. :P

**Comment by spetzel2020** [comment]
I am beginning work on 1.2. Is this Issue still relevant and wanted? Please respond in the next week, otherwise I will close (it can always be reopened)

**Comment by DrMcCoy** [comment]
Yes, please, thanks!

**Comment by DarioRomano** [comment]
> 

I disagree! I use Foundry with the module "monks common display" to show my players stuff and handle all my session needs via foundry. No one is logged into the session, but I would still love this feature to work, with PCs in general.

**Comment by spetzel2020** [comment]
Ok, gtn. If the status is available, I should be able to do some version of
this as an option.

**Comment by spetzel2020** [comment]
Added the option in 1.2.0b, and now need to plumb it to actually do something:
![image](https://github.com/spetzel2020/quick-encounters/assets/10853466/92fcdaa4-23ee-4306-94f9-64525a387054)

**Comment by spetzel2020** [comment]
1.2.0d: Removed "All" option because I don't know what it means (it would imply creating tokens for all players who weren't already in the scene). Happy to add back if somebody can explain how it should work.

**Comment by spetzel2020** [comment]
Implemented in 1.2.0f (not yet released). "Logged In" means any player token in the scene that is owned by a logged-in player (note that the player needs to be explicitly granted Owner, not just that the default access is Owner)

**Comment by spetzel2020** [comment]
(Pre)Released in 1.2.0. If you wish to test, manually install the manifest:
https://github.com/spetzel2020/quick-encounters/releases/download/v1.2.0/module.json

**Comment by DrMcCoy** [comment]
Thanks! :)

I'll test it when I find some time later this week.

**Comment by spetzel2020** [comment]
Released in 1.2.0

**Comment by DrMcCoy** [comment]
Okay, took me a bit to find some time to test this, and my regular sessions didn't actually do any fighting where I used QE in the past week.

The "In Scene" settings works great, it adds all player tokens. However, the "Logged In" setting doesn't; it instead just also adds all player tokens.

I do get an error in the debug console. No idea if that's related, because it also appears with the "In Scene" settings.

```
Uncaught (in promise) TypeError: this.previous is undefined
[Detected 1 package: quick-encounters]
    _manageTurnEvents foundry.js:21481
    _onCreate foundry.js:21319
    callback foundry.js:13525
    documents foundry.js:13498
    #handleCreateDocuments foundry.js:13498
    _createDocuments foundry.js:13359
    create commons.js:8594
    createDocuments commons.js:7923
    create commons.js:8046
    toggleCombat foundry.js:42508
    toggleCombat foundry.js:55640
    createCombat QuickEncounter.js:1628
    run QuickEncounter.js:1225
    setTimeout handler*run QuickEncounter.js:1224
    activateListeners QESheet.js:126
    jQuery 9
    activateListeners QESheet.js:124
    _render foundry.js:5766
    _render foundry.js:6456
    _render QESheet.js:91
    render foundry.js:5693
    displayQEDialog QuickEncounter.js:1935
    onRenderJournalPageSheet QuickEncounter.js:1885
    #call foundry.js:730
    callAll foundry.js:687
    _renderPageViews foundry.js:74702
    _render foundry.js:74665
    render foundry.js:5693
    render foundry.js:7035
    _onClickLeft2 foundry.js:52453
    callback foundry.js:31655
    #handleClickLeft2 foundry.js:31860
    #handleMouseDown foundry.js:31827
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerDown earcut.js:128
    mapEvent earcut.js:128
    onPointerDown earcut.js:128
foundry.js:21481:19
```

**Comment by DrMcCoy** [comment]
Oh, and my environment is this:
- Foundry VTT 11.308, hosted on a Debian server
- GM and player logged in using Firefox 116.0 on Linux
- System: Pathfinder 1 9.4
- Quick Encounters 1.2.0

**Comment by spetzel2020** [comment]
Great, thanks for the detailed info; I will take a look.

**Comment by spetzel2020** [comment]
Creating a new Issue for this: https://github.com/spetzel2020/quick-encounters/issues/139
