### ISSUE TITLE
Compatibility with Maestro?

### ISSUE THREAD

**Issue by Nysterian** [spetzel2020/quick-encounters#124]
I've been looking for something like this, however, in my games I use the module [Maestro](https://github.com/death-save/maestro) to setup different battle themes per encounter, since I have different battle themes for different enemy factions.

Is there any chance that an option to save a theme for maestro within each encounter JE?

**Comment by spetzel2020** [comment]
I am beginning work on 1.2. Is this Issue still relevant and wanted? Please respond in the next week, otherwise I will close (it can always be reopened)

**Comment by Nysterian** [comment]
This would still be great to have, yes!

**Comment by spetzel2020** [comment]
The next version of QE (v12) will be the last, and unfortunately I will not be implementing this enhancement in it.
