### ISSUE TITLE
Quick Encounter Map Note on the Scene

### ISSUE THREAD

**Issue by vampiregoat699** [spetzel2020/quick-encounters#129]
After creating an encounter it does NOT create the map note on the scene it is just gone no matter what I do I can't see them

**Comment by spetzel2020** [comment]
Can you check that Map Notes are set to show in the default view.  There is
a pin option in the Notes menu for this. In v10 I have been finding it
keeps turning off.

If that is still not working, please provide me exact steps  to reproduce.

**Comment by vampiregoat699** [comment]
ALL boxes are checked in the settings but nothing shows on map
![image](https://user-images.githubusercontent.com/124465461/230656961-a5381547-044a-4196-a391-8d12ff8c371c.png)

**Comment by spetzel2020** [comment]
No thats not what I meant. In Foundry, in the Map Notes view, are Map Notes
set to show all the time?

**Comment by vampiregoat699** [comment]
TY man do I feel dumb, still learning foundry

**Comment by spetzel2020** [comment]
Not at all! I keep forgetting that setting; it really should be in the main
view.
