### ISSUE TITLE
Support more than the "standard 7" dice; best would be to support all Foundry roll formulas

### ISSUE THREAD

**Issue by tuirgin** [spetzel2020/quick-encounters#137]
Great module that goes some distance to bridge the gap with Fantasy Ground's encounters system!

However, it seems like maybe only the "standard 7" dice are recognized. The following rolls are rejected: 1d3, 1d5, 1d7. And I've confirmed that I can't do workarounds like `{1d4-1}min1` or `ceil(1d6/2)`. It'd be nice if the quick encounter `input.num-actors` supported all Foundry roll formulas. Barring that, at least any arbitrary XdY formulation would be nice. 1d3 isn't uncommon in old school adventures—I've run into them prepping Stonehell, for example—and DCC has its funky array of non-platonic dice.

Regardless, this module is a lot of help when I need it. So, thanks!

![image](https://github.com/spetzel2020/quick-encounters/assets/97160/92fe5056-f374-41d0-bf0d-07cbd0b754bb)

**Comment by spetzel2020** [comment]
Thanks! Adding a few more is easy, but best wouldbe supporting Foundry roll
formulas which I'll have to do more research into. One possibility is
checking and warning, but otherwise only giving a runtime error if Foundry
rejects the actual roll.

**Comment by spetzel2020** [comment]
`getNumActors` only validates using `Roll.validate()` which should accept all Foundry legal rolls. That suggests that roll formulae extracted from Journal entries will work, but that some extrat validation is being done on ones entered through the QE dialog.

**Comment by spetzel2020** [comment]
Fixed in 1.2.2a (not yet released)
However, the edit field in the QEDialog needs to be expanded to allow these more complicated formulae.
Also, nonsense entries are being accepted so need to check what error conditions `Roll.validate()` throws

**Comment by spetzel2020** [comment]
In 1.2.2b (not yet released): Expanded QEDialog field to accommodate larger formulas
Seems to be catching simple garbage with an pop-up error from Foundry

**Comment by spetzel2020** [comment]
Released in 1.2.2
