### ISSUE TITLE
Foundry v12: Tutorial QE not showing text (blank)

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#146]
Only problem I still have is the tutorial is always blank and creates a new JE for each time I click it with no icons selected.  
_Originally posted by @kylania in https://github.com/spetzel2020/quick-encounters/issues/142#issuecomment-2177832755_

**Comment by spetzel2020** [comment]
Two possible problems here:

1. Missing text for the Tutorial
2. The Tutorial QE should be deleted after being shown

**Comment by spetzel2020** [comment]
Fixed in 12.1.1 (not yet Released)

**Comment by spetzel2020** [comment]
Pre-released in 12.1.1
@kylania You can test a pre-release by going to the Setup Screen, Add-On Modules tab. Instead of updating Quick Encounters directly, click on `Install Module` and then in the `Manifest URL` field, type:
`https://github.com/spetzel2020/quick-encounters/releases/download/v12.1.1/module.json`

This will install v12.1.1 pre-release. Let me know whether that fixes the QE Tutorial showing problem.

**Comment by kylania** [comment]
Yup!  Can confirm v12.1.1 properly displays the text for the tutorial and both internal and external links work.  It also properly deletes the JE when you close the window rather than duplicating.

Thanks!

**Comment by spetzel2020** [comment]
Great to hear - thanks for the quick confirmation.

**Comment by spetzel2020** [comment]
Released in 12.1.1
