### ISSUE TITLE
Request: Share encounters across worlds

### ISSUE THREAD

**Issue by drkranger71** [spetzel2020/quick-encounters#15]
It seems currently, the tokens lose their link to the encounter journal entry when shared to a different world.  The journal entries, scenes, and actors are all saved to a compendium which is attached to a a shared module.  That module is activated in a different world and the items in the shared compendium are imported into their respective locations.  Everything shares fine: the journals themselves, the tokens, the scenes, the journal labels on the scenes, but upon clicking on a quick encounter journal entry the token has a broken link icon and doesn't work even though the token is in the actor's folder with the same folder tree setup.  Any way to make this work?

**Comment by spetzel2020** [comment]
I was not aware of this problem but will take a look.

**Comment by drkranger71** [comment]
Some more testing for you.  When I posted the issue I was dragging tokens from compendiums onto the scene and using those to create the encounter.  I see now that you have another issue regarding that.  I don't remember if I had the same problem when running encounters created in the world with tokens pulled from compendiums, however.

For this issue, I thought it might be related to pulling the tokens from compendiums and not from the actor tab, but it's not.  I pulled tokens directly from the actor tab, saved everything in my shared module and imported everything into a new world from that shared module.  Still doesn't work.

In looking at the journal entry, it appears like the token ID is saved to the journal which would tell me that ID changes in a new world.  If it does, is there a search function to iterate through actors to find an equivalent by some other identifier?

Oh, if it matters, I'm also creating the encounters via the toolbar button: selecting dropped actors, clicking the button, creating the journal entry encounter, clicking save.  I think that's method 1.

**Comment by spetzel2020** [comment]
Great - that's helpful testing.

**Comment by spetzel2020** [comment]
Can you tell me the sequence that you are using to achieve this: _The journal entries, scenes, and actors are all saved to a compendium which is attached to a a shared module._

I tried it myself to reproduce but must be doing something wrong.

**Comment by drkranger71** [comment]
I followed these instructions, https://www.reddit.com/r/FoundryVTT/comments/fvw3c7/how_to_create_a_tiny_module_for_shared_content/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1, which is just a small unpublished, private module.  Activating the module creates the compendiums.  Dragging items to those compendiums saves those items.  Activating that module on different worlds, makes whatever is saved in the compendium available to that world...thus sharing items across worlds.

So, the actors, scenes, journal entries are all saved to the above shared module compendiums and then are available across worlds if the module is activated there.

**Comment by drkranger71** [comment]
I don't know enough yet about the macro or code creation, but the programming language is familiar.  If the issue with sharing tokens across worlds is the problem because the tokenID changes, then searching for the token/actor name and linking it might be the solution.  In the FVTT Community Macros, there is a macro called Link Token to Actor.  It uses the .find method to link tokens on the map scene with game actor tokens.  Maybe that will help.  I have copied the code from that macro here.

`const scene = game.scenes.active;
const unlinked = canvas.scene.data.tokens.map(t => {
    const actor = game.actors.entities.find(a => a.name === t.name);
    if (actor) {
        return {
            _id: t._id,
            actorId: actor.id
        }
    } else {
        console.log(t.name);
        return {
            _id: t._id,
            actorId: ""
        }
    }
});
const updates = duplicate(unlinked);

scene.updateEmbeddedEntity("Token", updates);

ui.notifications.info('Tokens linked to actors.');
console.log(updates);`

**Comment by drkranger71** [comment]
I did figure out how to retrieve a token/actor ID.  So, if the journal entry is storing the actor ID, then it is changing in different worlds.  The first image is one world with the tokens/actors and the second image is a different world with the same tokens/actors.

World 1:
![tokens1](https://user-images.githubusercontent.com/74797793/100264164-560c8300-2f03-11eb-8793-dc0c6e555358.png)

World 2:
![tokens2](https://user-images.githubusercontent.com/74797793/100264175-59077380-2f03-11eb-8a9a-5f1c0a851a49.PNG)

**Comment by spetzel2020** [comment]
I believe[ Scene Packer ](https://foundryvtt.com/packages/scene-packer) will allow you to package up Scenes with transportable IDs, and its more recent versions support Quick Encounters.

**Comment by drkranger71** [comment]
I'll check this out.  Thanks!

**Comment by spetzel2020** [comment]
COnfirm that Scene Packer addresses this

**Comment by spetzel2020** [comment]
Based on my understanding that Scene Packer addresses this, I am closing it.
