### ISSUE TITLE
Wildcard Randomization

### ISSUE THREAD

**Issue by Hebelios** [spetzel2020/quick-encounters#16]
Heya!
It seems like Foundry's wildcard token randomization doesn't seem to work in conjunction to method 2?

When using method 2 it gives the error "The provided media file does not have a valid image or video file extension" when the token is set as _commoner*_ and places mystery-men when using _commoner*.png_ for example.

(edit: Sorry, I'm new to github and didn't know how to add the Bug-tag)

**Comment by spetzel2020** [comment]
Thanks for the clear report and I'll take a look at this.

**Comment by spetzel2020** [comment]
This is fixed in v0.6.11 (latest release); let me know how it works for you!
