### ISSUE TITLE
Feature request: Add option to not add the combatants to the tracker

### ISSUE THREAD

**Issue by caewok** [spetzel2020/quick-encounters#34]
When running encounters with a lot of creatures (say, 50 kobolds), I usually use temporary combatants (using [Combat Utility Belt](https://github.com/death-save/combat-utility-belt)) to split them into "squads." Otherwise, I feel that combat takes too long if I have to step through each one-by-one, and the combat tracker gets a bit out of control. 

Thus, it would be useful to have an option when starting a quick encounter that would add the combatants to the map, but not the combat tracker. I thought this could be something you add to the new quick encounter dialog, maybe a toggle that defaults to yes for whether you want to add the combatants to the tracker.

**Comment by spetzel2020** [comment]
Good idea! I completely agree with your comment about "50 kobolds" taking too long (I'm actually planning another module to help with Mass Combat).

I think your idea fits well with my plans for 0.7.

**Comment by Shuggaloaf** [comment]
@spetzel2020 Hey there Spetzel. I see you removed this as a milestone. Is it still in plans for future versions or did you decide to just fully move this feature to your planned Mass Combat mod?

**Comment by spetzel2020** [comment]
I like the simple idea of having a checkbox next to each Actor to not add the tokens to the Combat Tracker. An even simpler idea would be an accelerator key (like the current Ctrl- and Alt- which force adding visible/invisible)

**Comment by Shuggaloaf** [comment]
I could actually see both of those being useful. The checkboxes would be nice for encounters where there are visible enemies but also hidden ones as well. And then the accelerator key is nice when you just want to drag out a group without adding to the tracker. I could see this being useful no only for combat but any non-combat scenes where you want to drag a group of NPCs into the scene.

**Comment by spetzel2020** [comment]
In 0.9.3d
Still need to check for use of Foundry 0.9 deprecated functions and then should be able to release this

**Comment by spetzel2020** [comment]
Released in v0.9.3
