### ISSUE TITLE
Option to disable Quick-Encounters for chosen entries

### ISSUE THREAD

**Issue by Hebelios** [spetzel2020/quick-encounters#36]
Have some kind of option to toggle a journal to be a quick-encounter or deactivate it.
It can be quite annoying to have the quick-encounter dialogue open every time you click a journal-entry with actors in.

**Comment by spetzel2020** [comment]
Definitely! I thought this was already in my plan, but apparently not.

What sort of control would work for you? I'm thinking of a simple checkbox in the Journal Entry itself so that you could toggle it on again. It can't be in the Quick Encounter dialog because then it would be turned off forever.

**Comment by Hebelios** [comment]
Checkbox in the journal itself might add a bit of clutter but I think that would probably work best.
Little checkbox on the bottom of the journal.

Other idea I had was a context-menu entry for journals.
Right click on the entry -> Quick-Encounter Options
Expanding on additional options in the future will be easier that way, although it will make it more "hidden away" I guess.

**Comment by spetzel2020** [comment]
Added:
- Setting to auto-show Quick Encounters (default Yes)
- Hide button on the QE dialog border to hide individual QEs
- Show button on the JE border to re-show a hidden (or closed) QE

Released in v0.7.3 (should update when you check).
