### ISSUE TITLE
Trigger Encounters by Macro

### ISSUE THREAD

**Issue by Noshei** [spetzel2020/quick-encounters#41]
Would really love to be able run an encounter from a macro command.

**Comment by spetzel2020** [comment]
Good idea - what would the function call and parameters look like to provide what you need?

**Comment by Noshei** [comment]
Probably something like:
runQuickEncounter(@JournalEntry[1dei1bAxcaOYEWp1]{M03. Library})

I'm not very familiar with macros in foundry yet (still new to foundry), but I think something like this would work.  I'm assuming that you associate the encounter with the journal entry, so just a link to the journal should be enough.

So the reason that I want this is so that I can use the Trigger Happy module to trigger an encounter when a player does some action (moves to a certain location, clicks on a book, etc).

**Comment by spetzel2020** [comment]
To investigate in 1.1

**Comment by spetzel2020** [comment]
Taking a look at this now, but QuickEncounters doesn't appear to be in scope for Macros, so I'm not sure how to call a specific one.

**Comment by spetzel2020** [comment]
I am beginning work on 1.2. Is this Issue still relevant and wanted? Please respond in the next week, otherwise I will close (it can always be reopened)

**Comment by spetzel2020** [comment]
Closing because of lack of response
