### ISSUE TITLE
Popup not opening with fr-FR Core module activated

### ISSUE THREAD

**Issue by Nadoteki** [spetzel2020/quick-encounters#42]
Hello, I'm a french user of foundry VTT. I try to use this module with the fr-FR Core module activated. It seems that the module prevent the popup windows to appear and make the "show" button on top of the note's windows too. Foundry is version 7.9 and Quick encounter is 0.7.3.
The error in the console is :
*foundry.js:4481 TypeError: An error occurred while rendering QESheet 48: Cannot set property 'label' of undefined
    at QESheet._getHeaderButtons (QESheet.js:76)
    at QESheet._renderOuter (foundry.js:4619)
    at QESheet._render (foundry.js:4527)
    at async QESheet._render (foundry.js:5157)*

**Comment by spetzel2020** [comment]
Sorry the delay in responding. I should be working on QE this week and will look at your issue this week - thanks for reporting it!

**Comment by spetzel2020** [comment]
Sorry for the delay on this. I've tracked down the problem to two things:
- a bug in my code when it checks for whether a button label was found
- an apparent lack of  usage of the French equivalent for the "Close" button
Planned to fix in 0.8.1

**Comment by spetzel2020** [comment]
Released in 0.8.1
