### ISSUE TITLE
Make a Quick Encounter a specialized type of entry, with a custom companion dialog with the Journal Entry

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#6]
2.  _I think you could do more with this application if a quick encounter entry was a specialized type of entry_ Very true. I was trying to avoid a completely separate setup process because of trying to handle the use-case like yours, of having MANY entries with Actors, and just wanting to use them. But I could definitely attach a specialized pop-up to Journal Entries you designate in this way, with the sort of options for the deployment pattern etc. That would also solve a UI problem, because I want to add a separate dialog showing which Actors have already been positioned (akin to Fantasy Grounds Encounter feature)

_Originally posted by @opus1217 in https://github.com/opus1217/quick-encounters/issues/4#issuecomment-703294604_

**Comment by opus1217** [comment]
Possible solution: Have a specialized Dialog that pops up next to a Quick Encounter Journal Entry.
- Would automatically pop up the first time you opened a Journal Entry with embedded Actors; you could turn it off or leave it on
- Would also incorporate the placement of tokens akin to Fantasy Grounds Encounters feature 
- Feature to say how tokens should be deployed by default

**Comment by spetzel2020** [comment]
Implemented in v0.6.1
