### ISSUE TITLE
Feature Request - Lootsheet Support

### ISSUE THREAD

**Issue by DanielBoettner** [spetzel2020/quick-encounters#60]
With a PR (which I will create and link later on) [LootSheetNPC5e](https://github.com/jopeek/fvtt-loot-sheet-npc-5e) will offer a method to convert Tokens to a lootable Sheet.

This could be used at the end of an encounter to convert all Tokens to be lootable by the players.

As discussed a call could look like this.
```js
// some numbers options to be used by the convert method
let options = {
     dmgMods: {chance: chance, mod:mod, foo:true, round: this.encounter.rounds},
     flavor: {style: style}
}

const { convertToken } =  game.modules.get("lootshettnpc5e").API;
 for (npc in npcs) {
    await convertToken (npc, options);         
 }
```

Where the LootSheet would use these options to convert the token to
use the "loot" sheet, set permissions for the players to view the sheet
and maybe apply some cool style.

The offered method behind this is a modified version of https://github.com/DFreds/dfreds-pocket-change/blob/fef6c383988f4dc0df7db84f3b7da99d98202e09/scripts/pocket-change.js#L197

**Comment by spetzel2020** [comment]
Great idea; won't be in 0.9.0 but should be able to add in a subsequent 0.9.x

**Comment by spetzel2020** [comment]
I'm finally getting to some enhancements in v1.0 of QE; how should I proceed with this one?

**Comment by DanielBoettner** [comment]
@spetzel2020 hey, great to hear this. :)

I'll ping you on discord in the near future. So we can have a talk before we plan along in issues. :)

**Comment by spetzel2020** [comment]
@DanielBoettner Any interest in this getting into 1.1? I can take a look at it unless you have a PR :)

**Comment by spetzel2020** [comment]
Going to close this as `wontfix` unless I hear interest for doing it.
