### ISSUE TITLE
Feature: Creature name/number at top of QE journal entry

### ISSUE THREAD

**Issue by weepingminotaur** [spetzel2020/quick-encounters#61]
Why? Because then you can view those details when mousing over the QE icon on the map instead of getting the standard boiler plate about QE functions on every QE icon. I'd much rather see "5x orcs / 1x ghoul" on mouseover than a basic explanation of how QE functions. :)

**Comment by spetzel2020** [comment]
Great idea - i'll take a look

**Comment by spetzel2020** [comment]
> Why? Because then you can view those details when mousing over the QE icon on the map instead of getting the standard boiler plate about QE functions on every QE icon. I'd much rather see "5x orcs / 1x ghoul" on mouseover than a basic explanation of how QE functions. :)

Actually I'm confused. I can certainly replace the boilerplate text IN the JE and replace it with a summary of the encounter. But a mouseover of the Note on the Scene will just show the name of the Note (which by default is the name of the JE) - right?

Can you provide a screenshot of which particular entity would look different so I understand?

**Comment by weepingminotaur** [comment]
Ah yes. I forgot that I had the Pin Cushion module enabled, which provides you with a snippet of preview text from any pin when you hover over it. So if the encounter summary is right at the top of the JE, it will display on mouseover.
