### ISSUE TITLE
Name is undefined.

### ISSUE THREAD

**Issue by Malekal4699** [spetzel2020/quick-encounters#69]
While QE works within the same game, exporting QE to a compendium and importing it to another game does not work.

Names, Images, etc don't seem to be processed correctly.
Entries are in the compendium, so are the journals.

![image](https://user-images.githubusercontent.com/78604153/143499892-e4814f46-21a6-4ae3-a5d4-211f4c116df3.png)
![image](https://user-images.githubusercontent.com/78604153/143500454-c024e632-cc75-41c3-bde1-aade9d7176ea.png)
![image](https://user-images.githubusercontent.com/78604153/143500535-08aaf56d-a1bd-4941-acbe-3a72a79b9930.png)

**Comment by spetzel2020** [comment]
Regrettably, vanilla QE will not work when exported/imported unless you are
using the default (SRD) monsters.

However, check out Scene Packer:
https://foundryvtt.com/packages/scene-packer
I have not used it but understand it works with Quick Encounters.

**Comment by Malekal4699** [comment]
That's actually how I migrated them over to the other game. 
Might have to read the process again.

**Comment by spetzel2020** [comment]
Ok, definitely let me and the other dev know if it's not working per
instruction.

**Comment by Malekal4699** [comment]
Alright, 3rd time's the charm. lol no clue what I did wrong. but it worked this time around.

**Comment by spetzel2020** [comment]
Glad it worked! And always happy to get feedback on QE.
