### ISSUE TITLE
Feature Request: Scene Independent Encounters

### ISSUE THREAD

**Issue by QcGreywolf** [spetzel2020/quick-encounters#71]
Desired Feature: Everything works exactly the same as it does now, but we can create a collection of actors to drop anywhere, in any scene wherever we drag from the entry to the scene. With one mouse motion and without having to manipulate notes, entries and journals.

It would still be useful even if it dropped a pile of actors all on top of each other.

My method of planning for homebrew, or even campaign modifications, revolves around the ability to reuse templates when its economical. And the ability to drop "1d4+2 OrcMooks" is AMAZING! But useless to me if it is linked to a specific scene.

**Comment by spetzel2020** [comment]
Thanks - I can now visualize what you're saying. If I'm understanding correctly the flow would be:
1. Create a new Journal Entry (or modify an existing one) called (say) **1d4+2 Orc Mooks**
2. Drag Actors into the JE (say 1d4+2 Orc Mooks) - when you save the JE it will also create the QE dialog
3. When you want to use that JE, just drag it onto the Scene and drop it where you want the Encounter to happen; QE would basically run the Quick Encounter immediately by generating and randomly distributing the tokens around the drop point.
4. You probably don't want a Map Note created (in fact I realize that QE will get quite confused if you have multiple Map Notes on the same Scene for the same Encounter)

**Comment by spetzel2020** [comment]
I think I can do this by intercepting the Map Note creation (when you drag the QE onto the Scene) and asking if you want a persistent Quick Encounter on the map, or an "Instant" Quick Encounter.

**Comment by QcGreywolf** [comment]
That pretty accurately sums up the thoughts on my case use.   
  

  
I’m an old timer used to years and years of Maptool, and that’s how I did it in that program. I liked the ability to just toss around piles of tokens and fine tuning their position after the initial drop.   
  

  
I’ve yet to get into coding with Foundry yet. You module coders are the real heroes of Foundry. Stock, it’s kinda rough around the edges.   
  
  
  
    
  

  
  
>

**Comment by spetzel2020** [comment]
Got diverted with some bugs in QE; hope to get back to this in the next few days

**Comment by spetzel2020** [comment]
In progress with 1.0.1

**Comment by spetzel2020** [comment]
Implemented in 1.0.1

**Comment by spetzel2020** [comment]
Release in 1.0.1: https://github.com/spetzel2020/quick-encounters/releases/latest/download/module.json
