### ISSUE TITLE
Incompatible with Core V9 Stable (Build 238)

### ISSUE THREAD

**Issue by sneat** [spetzel2020/quick-encounters#72]
Quick Encounters doesn't seem to be working for me with the current version of Foundry VTT.

Version: V9 Stable (Build 238)
Platform: Linux/NodeJS

Clicking on the fist icon in the toolbar throws the following error:
```
QuickEncounter.js:417 Uncaught ReferenceError: TOKEN_DISPOSITIONS is not defined
[Detected 1 package: quick-encounters]
    at Function.runAddOrCreate (QuickEncounter.js:417)
    at Object.onClick (QuickEncounter.js:389)
    at SceneControls._onClickTool (foundry.js:51380)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)
```

This is because `isFoundryV9 = game.data.version.startsWith("0.9");` is `false` for me.

```
game.data.version
> foundry.js:5069 game.data.version is deprecated since V9 in favor of game.version
> '9.238'
```

If I edit that so that it checks `.startsWith("9");` throughout the code then I get the following error:
```
QuickEncounter.js:428 Uncaught TypeError: Cannot read properties of undefined (reading 'controlled')
[Detected 1 package: quick-encounters]
    at Function.runAddOrCreate (QuickEncounter.js:428)
    at Object.onClick (QuickEncounter.js:389)
    at SceneControls._onClickTool (foundry.js:51380)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)
```
Because `Tile.layer` is undefined.

I *think* that this should instead be `canvas.background.controlled` and/or `canvas.foreground.controlled`.

Making that change as well allows the Fist icon to show the normal dialog, but journals with quick encounter data don't seem to pop up the normal dialog.

Let me know if I can provide anything else.

**Comment by spetzel2020** [comment]
Thanks for the report! I have **just** started testing with Foundry v9; the quick release of a stable version caught me by surprise.

It sounds like I should be able to fix the "if isFoundryV9" problem pretty quickly and then see how that places things.

**Comment by spetzel2020** [comment]
Turns out the warning is a red-herring; although game.data.version is deprecated, it still returns the correct information. The actual problem is the (silent) deprecation of journal.entity and its replacement with journal.object.

There will be a QE 0.9.5 to fix this.

**Comment by spetzel2020** [comment]
Fixed and released in [0.9.5](https://github.com/spetzel2020/quick-encounters/releases/latest/download/module.json)

**Comment by sneat** [comment]
Very quick turnaround and it's all working for me now. Thank you :)

**Comment by spetzel2020** [comment]
Thanks! Great to hear!
