### ISSUE TITLE
QE Scene Icon disappears

### ISSUE THREAD

**Issue by GrumpyVader** [spetzel2020/quick-encounters#85]
When I create a QE, the scene icon is initially created along with the Journal entry. If I refresh the scene (F5), the icon no longer displays. If I then try to drop the Journal entry on to the scene, the Icon displays again. I had thought it was a conflict with Monk's Enhanced Journals, but I removed MEJ and the behavior persists. 

![image](https://user-images.githubusercontent.com/39166319/157980644-ec25f709-1f3f-4a6f-89bc-4316dc72f702.png)
![image](https://user-images.githubusercontent.com/39166319/157980904-980d35a0-037e-428b-ad73-955f5e34083d.png)

**Comment by spetzel2020** [comment]
Sorry to ask the basic question, but do you have the Map Notes displaying
for you when you're not in Journal mode? In other words, have you enabled
the little pin toggle in the Note submenu on the left side menu? (I find it
almost invisible to tell whether its on or off)

**Comment by GrumpyVader** [comment]
Great question. I always forget about that and I will check here in a minute.

**Comment by GrumpyVader** [comment]
Crap, that was it. Sorry for the false alarm.

**Comment by GrumpyVader** [comment]
I think it should default to On. But that is just me and I know that is a Core Foundry thing. I will close this issue out. Thanks for your help.
