### ISSUE TITLE
Adding a default folder for new journal entry

### ISSUE THREAD

**Issue by davelacorneille** [spetzel2020/quick-encounters#94]
When QE create a new entry journal, would it be possible to place it in a predefined folder.

Thanks you

**Comment by spetzel2020** [comment]
Good idea - should be possible after I get QE working (again) with Foundry v10.

I imagine specifying the Default Folder in QE Settings - would that work?

**Comment by davelacorneille** [comment]
Yeah really! 😇

Coming from Fantasy ground, I didn't why this functionality was in Foundry!
Thank you so much for your help!

**Comment by spetzel2020** [comment]
Fixed (not released) in 1.1.0d
However, still needs warning to be i18n'd

**Comment by spetzel2020** [comment]
Released in 1.1.0 (will fix i18n issues with others)
